export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_USER: "SET_USER",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_ARTISTS: "SET_ARTISTS",
  SET_TRACKS: "SET_TRACKS",
  SET_FEATUREDPLAYLISTS: "SET_FEATUREDPLAYLISTS",
  SET_RECENTLYPLAYED: "SET_RECENTLYPLAYED",
  SET_PLAYING: "SET_PLAYING",
  SET_PLAYER_STATE: "SET_PLAYER_STATE",
};
